"""initial

Revision ID: 354d95970f2c
Revises: 
Create Date: 2025-10-02 18:10:51.656314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354d95970f2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('efeito', sa.String(length=300), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('guilda_vencedora', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('defesa', sa.Integer(), nullable=True),
    sa.Column('vida', sa.Integer(), nullable=True),
    sa.Column('habilidade', sa.String(length=200), nullable=True),
    sa.Column('efeito', sa.String(length=300), nullable=True),
    sa.Column('death_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('death_tokens', sa.Integer(), nullable=True),
    sa.Column('curse_nome', sa.String(length=100), nullable=True),
    sa.Column('curse_valor', sa.Integer(), nullable=True),
    sa.Column('curse_efeito', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_map')
    op.drop_table('hero')
    op.drop_table('map')
    op.drop_table('guild')
    op.drop_table('curse')
    op.drop_table('campaign')
    # ### end Alembic commands ###
